import type { Category, Product } from '../../lib/types'
import type { PromoCode } from '../../store/cart'

export const SHOP_CATEGORIES: Category[] = [
  { id: 'laptops', name: 'Ноутбуки', glyph: '💻' },
  { id: 'phones', name: 'Смартфоны', glyph: '📱' },
  { id: 'audio', name: 'Аудио', glyph: '🎧' },
  { id: 'watch', name: 'Часы', glyph: '⌚' },
  { id: 'photo', name: 'Фото и видео', glyph: '📷' },
  { id: 'accessories', name: 'Аксессуары', glyph: '🔌' },
]

export const SHOP_BRANDS = ['Nordline', 'Kvant', 'Aurum', 'Vektor', 'Helix']

export const SHOP_PROMO_CODES: Record<string, PromoCode> = {
  SALE10: { percent: 10, label: 'Скидка 10 % на заказ' },
  TECH15: { percent: 15, label: 'Минус 15 % на технику' },
}

export const SHOP_DELIVERY_FEE = 490
export const SHOP_FREE_DELIVERY_FROM = 5000

export const SHOP_PRODUCTS: Product[] = [
  {
    id: 'lp-nord-14',
    name: 'Nordline Air 14',
    description: 'Лёгкий ноутбук для работы и учёбы: 14 дюймов, 16 ГБ памяти и 18 часов автономности.',
    price: 89990,
    oldPrice: 104990,
    category: 'laptops',
    brand: 'Nordline',
    glyph: '💻',
    hue: 212,
    badge: 'Хит',
    rating: 4.8,
    reviews: 341,
    specs: [
      { label: 'Экран', value: '14", 2560 × 1600, 120 Гц' },
      { label: 'Память', value: '16 ГБ / 512 ГБ SSD' },
      { label: 'Вес', value: '1,24 кг' },
      { label: 'Автономность', value: 'до 18 часов' },
    ],
  },
  {
    id: 'lp-kvant-pro',
    name: 'Kvant Pro 16',
    description: 'Рабочая станция для монтажа и 3D: 16 дюймов, дискретная графика, 32 ГБ памяти.',
    price: 179990,
    category: 'laptops',
    brand: 'Kvant',
    glyph: '🖥️',
    hue: 232,
    rating: 4.9,
    reviews: 128,
    specs: [
      { label: 'Экран', value: '16", 3072 × 1920, 165 Гц' },
      { label: 'Память', value: '32 ГБ / 1 ТБ SSD' },
      { label: 'Графика', value: 'дискретная, 12 ГБ' },
      { label: 'Вес', value: '2,1 кг' },
    ],
  },
  {
    id: 'lp-vektor-13',
    name: 'Vektor Book 13',
    description: 'Бюджетный ноутбук для документов и браузера. Тихий, без вентилятора.',
    price: 42990,
    oldPrice: 49990,
    category: 'laptops',
    brand: 'Vektor',
    glyph: '📓',
    hue: 196,
    rating: 4.3,
    reviews: 217,
    specs: [
      { label: 'Экран', value: '13,3", 1920 × 1200' },
      { label: 'Память', value: '8 ГБ / 256 ГБ SSD' },
      { label: 'Вес', value: '1,1 кг' },
    ],
  },
  {
    id: 'ph-aurum-x',
    name: 'Aurum X Pro',
    description: 'Флагманский смартфон с тройной камерой и экраном 120 Гц. Снимает видео в 4K.',
    price: 119990,
    category: 'phones',
    brand: 'Aurum',
    glyph: '📱',
    hue: 44,
    badge: 'Новинка',
    rating: 4.9,
    reviews: 512,
    specs: [
      { label: 'Экран', value: '6,7", AMOLED, 120 Гц' },
      { label: 'Камера', value: '50 + 12 + 10 Мп' },
      { label: 'Память', value: '256 ГБ' },
      { label: 'Батарея', value: '4800 мА·ч' },
    ],
  },
  {
    id: 'ph-kvant-lite',
    name: 'Kvant Lite 5',
    description: 'Смартфон среднего класса: большой экран, три дня автономности, быстрая зарядка.',
    price: 34990,
    oldPrice: 39990,
    category: 'phones',
    brand: 'Kvant',
    glyph: '📲',
    hue: 264,
    rating: 4.5,
    reviews: 389,
    specs: [
      { label: 'Экран', value: '6,5", IPS, 90 Гц' },
      { label: 'Камера', value: '48 + 8 Мп' },
      { label: 'Память', value: '128 ГБ' },
      { label: 'Батарея', value: '5500 мА·ч' },
    ],
  },
  {
    id: 'ph-helix-mini',
    name: 'Helix Mini',
    description: 'Компактный смартфон, который помещается в ладонь. Для тех, кому надоели лопаты.',
    price: 54990,
    category: 'phones',
    brand: 'Helix',
    glyph: '🤳',
    hue: 336,
    rating: 4.6,
    reviews: 146,
    outOfStock: true,
    specs: [
      { label: 'Экран', value: '5,4", AMOLED' },
      { label: 'Камера', value: '12 + 12 Мп' },
      { label: 'Память', value: '128 ГБ' },
    ],
  },
]

export const SHOP_PRODUCTS_AUDIO: Product[] = [
  {
    id: 'au-nord-buds',
    name: 'Nordline Buds 3',
    description: 'Беспроводные наушники с активным шумоподавлением и прозрачным режимом.',
    price: 14990,
    oldPrice: 18990,
    category: 'audio',
    brand: 'Nordline',
    glyph: '🎧',
    hue: 208,
    badge: 'Хит',
    rating: 4.7,
    reviews: 823,
    specs: [
      { label: 'Шумоподавление', value: 'активное, 3 режима' },
      { label: 'Автономность', value: '8 ч + 24 ч с кейсом' },
      { label: 'Защита', value: 'IPX4' },
    ],
  },
  {
    id: 'au-aurum-over',
    name: 'Aurum Studio One',
    description: 'Полноразмерные наушники для долгих сессий. Мягкие амбушюры, съёмный кабель.',
    price: 32990,
    category: 'audio',
    brand: 'Aurum',
    glyph: '🎙️',
    hue: 36,
    rating: 4.8,
    reviews: 274,
    specs: [
      { label: 'Тип', value: 'полноразмерные, закрытые' },
      { label: 'Автономность', value: 'до 40 часов' },
      { label: 'Вес', value: '268 г' },
    ],
  },
  {
    id: 'au-helix-speaker',
    name: 'Helix Sound Cube',
    description: 'Портативная колонка с защитой от воды. Играет 20 часов, соединяется в стерео-пару.',
    price: 9990,
    category: 'audio',
    brand: 'Helix',
    glyph: '🔊',
    hue: 152,
    rating: 4.5,
    reviews: 456,
    specs: [
      { label: 'Мощность', value: '30 Вт' },
      { label: 'Защита', value: 'IP67' },
      { label: 'Автономность', value: 'до 20 часов' },
    ],
  },
  {
    id: 'wt-vektor-fit',
    name: 'Vektor Fit 4',
    description: 'Фитнес-часы с пульсометром, GPS и оценкой сна. Работают неделю без подзарядки.',
    price: 12990,
    oldPrice: 15990,
    category: 'watch',
    brand: 'Vektor',
    glyph: '⌚',
    hue: 180,
    rating: 4.4,
    reviews: 612,
    specs: [
      { label: 'Экран', value: '1,4", AMOLED' },
      { label: 'Автономность', value: 'до 7 дней' },
      { label: 'Датчики', value: 'пульс, SpO₂, GPS' },
    ],
  },
  {
    id: 'wt-aurum-classic',
    name: 'Aurum Watch Classic',
    description: 'Смарт-часы в стальном корпусе с сапфировым стеклом. Строгий вид, умная начинка.',
    price: 44990,
    category: 'watch',
    brand: 'Aurum',
    glyph: '🕰️',
    hue: 40,
    badge: 'Новинка',
    rating: 4.7,
    reviews: 189,
    specs: [
      { label: 'Корпус', value: 'нержавеющая сталь, 42 мм' },
      { label: 'Стекло', value: 'сапфировое' },
      { label: 'Автономность', value: 'до 3 дней' },
    ],
  },
]

export const SHOP_PRODUCTS_REST: Product[] = [
  {
    id: 'ph-kvant-cam',
    name: 'Kvant Snap R7',
    description: 'Беззеркальная камера для съёмки видео и репортажа. Матрица APS-C, стабилизация.',
    price: 98990,
    category: 'photo',
    brand: 'Kvant',
    glyph: '📷',
    hue: 248,
    rating: 4.8,
    reviews: 97,
    specs: [
      { label: 'Матрица', value: 'APS-C, 26 Мп' },
      { label: 'Видео', value: '4K 60 к/с' },
      { label: 'Стабилизация', value: 'матричная, 5 осей' },
    ],
  },
  {
    id: 'ph-helix-action',
    name: 'Helix Action 5',
    description: 'Экшн-камера с защитой от воды до 10 метров. Снимает 4K и держит удары.',
    price: 27990,
    oldPrice: 32990,
    category: 'photo',
    brand: 'Helix',
    glyph: '🎥',
    hue: 168,
    rating: 4.6,
    reviews: 233,
    specs: [
      { label: 'Видео', value: '4K 120 к/с' },
      { label: 'Защита', value: 'до 10 м без бокса' },
      { label: 'Экран', value: 'два, спереди и сзади' },
    ],
  },
  {
    id: 'ac-nord-charger',
    name: 'Зарядка Nordline 65 Вт',
    description: 'Компактный блок питания на три устройства сразу. Заряжает ноутбук и два телефона.',
    price: 3990,
    category: 'accessories',
    brand: 'Nordline',
    glyph: '🔌',
    hue: 204,
    rating: 4.6,
    reviews: 518,
    specs: [
      { label: 'Мощность', value: '65 Вт' },
      { label: 'Порты', value: '2 × USB-C, 1 × USB-A' },
    ],
  },
  {
    id: 'ac-vektor-bank',
    name: 'Повербанк Vektor 20000',
    description: 'Аккумулятор на 20 000 мА·ч с быстрой зарядкой и дисплеем остатка заряда.',
    price: 5490,
    oldPrice: 6990,
    category: 'accessories',
    brand: 'Vektor',
    glyph: '🔋',
    hue: 132,
    rating: 4.5,
    reviews: 704,
    specs: [
      { label: 'Ёмкость', value: '20 000 мА·ч' },
      { label: 'Мощность', value: '45 Вт' },
      { label: 'Дисплей', value: 'есть' },
    ],
  },
  {
    id: 'ac-aurum-keyboard',
    name: 'Клавиатура Aurum Type',
    description: 'Механическая клавиатура с тихими переключателями и подсветкой. Три устройства по Bluetooth.',
    price: 11990,
    category: 'accessories',
    brand: 'Aurum',
    glyph: '⌨️',
    hue: 48,
    rating: 4.7,
    reviews: 312,
    specs: [
      { label: 'Переключатели', value: 'тихие линейные' },
      { label: 'Подключение', value: 'Bluetooth 5.3 / USB-C' },
      { label: 'Подсветка', value: 'белая, 5 уровней' },
    ],
  },
  {
    id: 'ac-helix-hub',
    name: 'Хаб Helix Port 7 в 1',
    description: 'Расширяет один USB-C до семи портов: HDMI, картридер, Ethernet и три USB.',
    price: 6490,
    category: 'accessories',
    brand: 'Helix',
    glyph: '🧩',
    hue: 288,
    rating: 4.4,
    reviews: 189,
    specs: [
      { label: 'Портов', value: '7' },
      { label: 'Видео', value: 'HDMI 4K 60 Гц' },
      { label: 'Сеть', value: 'Ethernet 1 Гбит/с' },
    ],
  },
]

/** Полный каталог магазина. */
export const SHOP_CATALOG: Product[] = [
  ...SHOP_PRODUCTS,
  ...SHOP_PRODUCTS_AUDIO,
  ...SHOP_PRODUCTS_REST,
]

export const SHOP_PRICE_MAX = Math.max(...SHOP_CATALOG.map((p) => p.price))
