// Файл создаётся скриптом scripts/build-photo-manifest.mjs — править руками не нужно.

/** Идентификаторы товаров, для которых в public/photos лежит фотография. */
const WITH_PHOTO = new Set<string>([
  'ac-aurum-keyboard',
  'ac-helix-hub',
  'ac-nord-charger',
  'ac-vektor-bank',
  'au-aurum-over',
  'au-helix-speaker',
  'au-nord-buds',
  'baked-crab',
  'baked-eel',
  'baked-salmon',
  'bd-cards',
  'bd-logic',
  'bd-quest',
  'cr-clay',
  'cr-paint',
  'cr-slime',
  'ct-blocks',
  'ct-castle',
  'ct-robot',
  'dessert-cheesecake',
  'dessert-mochi',
  'drink-cola',
  'drink-green-tea',
  'drink-lemonade',
  'ds-fondant',
  'ds-pavlova',
  'ds-tiramisu',
  'g-bar',
  'g-dish',
  'g-hall',
  'g-kitchen',
  'g-private',
  'g-terrace',
  'hot-gyoza',
  'hot-miso',
  'hot-ramen',
  'lp-kvant-pro',
  'lp-nord-14',
  'lp-vektor-13',
  'mn-duck',
  'mn-lamb',
  'mn-ribeye',
  'mn-seabass',
  'mn-vegetables',
  'nigiri-eel',
  'nigiri-salmon',
  'nigiri-tuna',
  'ot-bubbles',
  'ot-kite',
  'ot-scooter',
  'ph-aurum-x',
  'ph-helix-action',
  'ph-helix-mini',
  'ph-kvant-cam',
  'ph-kvant-lite',
  'ps-carbonara',
  'ps-truffle',
  'ps-vongole',
  'roll-alaska',
  'roll-california',
  'roll-dragon',
  'roll-philadelphia',
  'roll-spicy-tuna',
  'set-osaka',
  'set-tokyo',
  'set-veg',
  'sf-bear',
  'sf-fox',
  'sf-whale',
  'st-burrata',
  'st-hummus',
  'st-scallops',
  'st-tartare',
  'tr-cars',
  'tr-excavator',
  'tr-railway',
  'wn-barolo',
  'wn-chardonnay',
  'wn-prosecco',
  'wt-aurum-classic',
  'wt-vektor-fit',
])

/** Есть ли у товара настоящее фото. */
export function hasPhoto(id: string): boolean {
  return WITH_PHOTO.has(id)
}

/**
 * Адрес фотографии товара. Учитывает базовый путь сайта,
 * поэтому работает и в подпапке на GitHub Pages.
 */
export function photoUrl(id: string): string | undefined {
  return hasPhoto(id) ? `${import.meta.env.BASE_URL}photos/${id}.webp` : undefined
}
