import type { Category, Product } from '../../lib/types'
import type { PromoCode } from '../../store/cart'

// Обложка категории — фото одного из её блюд
export const SUSHI_CATEGORIES: Category[] = [
  { id: 'sets', name: 'Сеты', coverId: 'set-tokyo' },
  { id: 'rolls', name: 'Роллы', coverId: 'roll-philadelphia' },
  { id: 'baked', name: 'Запечённые', coverId: 'baked-salmon' },
  { id: 'sushi', name: 'Суши', coverId: 'nigiri-salmon' },
  { id: 'hot', name: 'Горячее', coverId: 'hot-ramen' },
  { id: 'drinks', name: 'Напитки', coverId: 'drink-lemonade' },
  { id: 'desserts', name: 'Десерты', coverId: 'dessert-mochi' },
]

export const SUSHI_PROMO_CODES: Record<string, PromoCode> = {
  ROLL15: { percent: 15, label: 'Минус 15 % на весь заказ' },
  FIRST10: { percent: 10, label: 'Скидка новому гостю' },
  VECHER20: { percent: 20, label: 'Вечерняя скидка 20 %' },
}

export const SUSHI_PRODUCTS: Product[] = [
  // ---------- Сеты ----------
  {
    id: 'set-tokyo',
    name: 'Сет «Токио»',
    description: '40 кусочков: Филадельфия, Калифорния, Дракон и Запечённый с угрём. Хватает на компанию из трёх человек.',
    price: 1990,
    oldPrice: 2490,
    category: 'sets',
    glyph: '🍱',
    hue: 352,
    badge: 'Хит',
    weight: '1250 г · 40 шт',
    rating: 4.9,
    reviews: 312,
    tags: ['Компании', 'Выгодно'],
  },
  {
    id: 'set-osaka',
    name: 'Сет «Осака»',
    description: 'Двадцать четыре кусочка классических роллов: Филадельфия, Аляска и Калифорния с крабом.',
    price: 1290,
    category: 'sets',
    glyph: '🥡',
    hue: 12,
    weight: '780 г · 24 шт',
    rating: 4.7,
    reviews: 186,
    tags: ['Двоим'],
  },
  {
    id: 'set-veg',
    name: 'Сет «Зелёный»',
    description: 'Овощные роллы с авокадо, огурцом, спаржей и болгарским перцем. Полностью постный состав.',
    price: 890,
    category: 'sets',
    glyph: '🥗',
    hue: 118,
    weight: '540 г · 24 шт',
    rating: 4.6,
    reviews: 74,
    tags: ['Вегетарианский'],
  },
  // ---------- Роллы ----------
  {
    id: 'roll-philadelphia',
    name: 'Филадельфия',
    description: 'Слабосолёный лосось, сливочный сыр, огурец и рис с нори. Классика, с которой начинают почти все.',
    price: 490,
    category: 'rolls',
    glyph: '🍣',
    hue: 14,
    badge: 'Хит',
    weight: '240 г · 8 шт',
    rating: 4.9,
    reviews: 528,
  },
  {
    id: 'roll-california',
    name: 'Калифорния',
    description: 'Краб, авокадо и огурец в икре тобико. Мягкий вкус без резкой рыбной ноты.',
    price: 430,
    category: 'rolls',
    glyph: '🍙',
    hue: 28,
    weight: '235 г · 8 шт',
    rating: 4.8,
    reviews: 401,
  },
  {
    id: 'roll-dragon',
    name: 'Дракон',
    description: 'Угорь, огурец и сливочный сыр под соусом унаги с кунжутом. Насыщенный сладко-солёный вкус.',
    price: 590,
    category: 'rolls',
    glyph: '🐉',
    hue: 268,
    weight: '260 г · 8 шт',
    rating: 4.8,
    reviews: 245,
    tags: ['Острый соус'],
  },
  {
    id: 'roll-alaska',
    name: 'Аляска',
    description: 'Лосось, креветка, авокадо и сливочный сыр. Сытный ролл с двумя видами морепродуктов.',
    price: 520,
    category: 'rolls',
    glyph: '🦐',
    hue: 6,
    weight: '250 г · 8 шт',
    rating: 4.7,
    reviews: 163,
  },
  {
    id: 'roll-spicy-tuna',
    name: 'Спайси тунец',
    description: 'Тунец, огурец и спайси-соус на основе японского майонеза. Заметно острый — предупреждаем заранее.',
    price: 550,
    category: 'rolls',
    glyph: '🌶️',
    hue: 358,
    weight: '230 г · 8 шт',
    rating: 4.6,
    reviews: 132,
    tags: ['Остро'],
  },
]

/* ---------- Запечённые ---------- */
export const SUSHI_PRODUCTS_BAKED: Product[] = [
  {
    id: 'baked-eel',
    name: 'Запечённый с угрём',
    description: 'Угорь и сливочный сыр под сырной шапкой, запечённые до румяной корочки. Подаём горячими.',
    price: 610,
    category: 'baked',
    glyph: '🔥',
    hue: 24,
    badge: 'Горячее',
    weight: '270 г · 8 шт',
    rating: 4.9,
    reviews: 208,
  },
  {
    id: 'baked-salmon',
    name: 'Запечённый с лососем',
    description: 'Лосось, сливочный сыр и соус спайси под запечённым сыром. Тянется при разломе.',
    price: 560,
    category: 'baked',
    glyph: '🧀',
    hue: 40,
    weight: '265 г · 8 шт',
    rating: 4.8,
    reviews: 174,
  },
  {
    id: 'baked-crab',
    name: 'Запечённый с крабом',
    description: 'Краб, огурец и японский майонез под сырной корочкой. Мягкий вариант для тех, кто не любит рыбу.',
    price: 490,
    category: 'baked',
    glyph: '🦀',
    hue: 8,
    weight: '260 г · 8 шт',
    rating: 4.6,
    reviews: 96,
  },
]

/* ---------- Суши ---------- */
export const SUSHI_PRODUCTS_NIGIRI: Product[] = [
  {
    id: 'nigiri-salmon',
    name: 'Суши с лососем',
    description: 'Ломтик слабосолёного лосося на рисовой подушке. Две штуки в порции.',
    price: 180,
    category: 'sushi',
    glyph: '🍤',
    hue: 18,
    weight: '60 г · 2 шт',
    rating: 4.8,
    reviews: 289,
  },
  {
    id: 'nigiri-eel',
    name: 'Суши с угрём',
    description: 'Копчёный угорь с соусом унаги и кунжутом. Две штуки в порции.',
    price: 230,
    category: 'sushi',
    glyph: '🍥',
    hue: 32,
    weight: '62 г · 2 шт',
    rating: 4.7,
    reviews: 141,
  },
  {
    id: 'nigiri-tuna',
    name: 'Суши с тунцом',
    description: 'Тунец блюфин, плотная текстура и чистый вкус без добавок. Две штуки в порции.',
    price: 210,
    category: 'sushi',
    glyph: '🐟',
    hue: 348,
    weight: '58 г · 2 шт',
    rating: 4.7,
    reviews: 118,
    outOfStock: true,
  },
]

/* ---------- Горячее ---------- */
export const SUSHI_PRODUCTS_HOT: Product[] = [
  {
    id: 'hot-ramen',
    name: 'Рамен с курицей',
    description: 'Наваристый куриный бульон, пшеничная лапша, яйцо аджитама, кукуруза и зелёный лук.',
    price: 490,
    category: 'hot',
    glyph: '🍜',
    hue: 36,
    weight: '450 мл',
    rating: 4.8,
    reviews: 167,
    tags: ['Согревает'],
  },
  {
    id: 'hot-gyoza',
    name: 'Гёдза со свининой',
    description: 'Шесть обжаренных пельменей с сочной начинкой и соевым соусом с кунжутом.',
    price: 350,
    category: 'hot',
    glyph: '🥟',
    hue: 44,
    weight: '210 г · 6 шт',
    rating: 4.7,
    reviews: 123,
  },
  {
    id: 'hot-miso',
    name: 'Мисо-суп',
    description: 'Паста мисо, тофу, водоросли вакамэ и зелёный лук. Классическое начало ужина.',
    price: 190,
    category: 'hot',
    glyph: '🍲',
    hue: 30,
    weight: '300 мл',
    rating: 4.5,
    reviews: 88,
  },
]

/* ---------- Напитки и десерты ---------- */
export const SUSHI_PRODUCTS_REST: Product[] = [
  {
    id: 'drink-green-tea',
    name: 'Зелёный чай сенча',
    description: 'Листовой японский чай в чайнике на две чашки. Подаём без сахара.',
    price: 240,
    category: 'drinks',
    glyph: '🍵',
    hue: 104,
    weight: '500 мл',
    rating: 4.6,
    reviews: 64,
  },
  {
    id: 'drink-lemonade',
    name: 'Лимонад юдзу',
    description: 'Домашний лимонад на японском цитрусе юдзу с мятой и льдом.',
    price: 290,
    category: 'drinks',
    glyph: '🥤',
    hue: 58,
    weight: '400 мл',
    rating: 4.7,
    reviews: 92,
    badge: 'Новинка',
  },
  {
    id: 'drink-cola',
    name: 'Кола',
    description: 'Охлаждённая кола в стеклянной бутылке.',
    price: 150,
    category: 'drinks',
    glyph: '🥫',
    hue: 20,
    weight: '330 мл',
    rating: 4.4,
    reviews: 51,
  },
  {
    id: 'dessert-mochi',
    name: 'Моти ассорти',
    description: 'Четыре рисовых пирожных с начинками: манго, матча, клубника и кокос.',
    price: 390,
    category: 'desserts',
    glyph: '🍡',
    hue: 320,
    weight: '160 г · 4 шт',
    rating: 4.8,
    reviews: 137,
    badge: 'Новинка',
  },
  {
    id: 'dessert-cheesecake',
    name: 'Чизкейк матча',
    description: 'Нежный японский чизкейк на зелёном чае с песочной основой.',
    price: 340,
    category: 'desserts',
    glyph: '🍰',
    hue: 96,
    weight: '140 г',
    rating: 4.6,
    reviews: 79,
  },
]

/** Полное меню — то, что рендерится на странице. */
export const SUSHI_MENU: Product[] = [
  ...SUSHI_PRODUCTS,
  ...SUSHI_PRODUCTS_BAKED,
  ...SUSHI_PRODUCTS_NIGIRI,
  ...SUSHI_PRODUCTS_HOT,
  ...SUSHI_PRODUCTS_REST,
]

/** Стоимость доставки и порог бесплатной доставки. */
export const SUSHI_DELIVERY_FEE = 250
export const SUSHI_FREE_DELIVERY_FROM = 1500
